/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.apistudio.controller;import cn.zhuatech.apistudio.service.RequestPlanService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                   */
@RestController @RequestMapping("/api/apistudio") @CrossOrigin public class RequestPlanController{private final RequestPlanService s;/**
                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                        */
public RequestPlanController(RequestPlanService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                     */
@PostMapping("/plan") RequestPlanService.Result plan(@Valid @RequestBody RequestPlanService.Request r){return s.plan(r);}}
